{{- if .Values.create.schedule }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "snapshot-cli.fullname" . }}-create
  labels:
    {{- include "snapshot-cli.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.create.schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: {{ .Chart.Name }}-create
              securityContext:
                {{- toYaml .Values.securityContext | nindent 16 }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              args:
                {{- toYaml .Values.create.args | nindent 16 }}
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
              env:
              - name: OS_AUTH_URL
                {{- if .Values.openstack.enabled }}
                secretRef:
                  name: {{ .Values.openstack.secretName }}
                  key: OS_AUTH_URL
                {{- else }}
                value: "{{ .Values.openstack.OS_AUTH_URL }}"
                {{- end }}
              - name: OS_USERNAME
                {{- if .Values.openstack.enabled }}
                secretRef:
                  name: {{ .Values.openstack.secretName }}
                  key: OS_USERNAME
                {{- else }}
                value: "{{ .Values.openstack.OS_USERNAME }}"
                {{- end }}
              - name: OS_PASSWORD
                {{- if .Values.openstack.enabled }}
                secretRef:
                  name: {{ .Values.openstack.secretName }}
                  key: OS_PASSWORD
                {{- else }}
                value: "{{ .Values.openstack.OS_PASSWORD }}"
                {{- end }}
              - name: OS_USER_DOMAIN_NAME
                {{- if .Values.openstack.enabled }}
                secretRef:
                  name: {{ .Values.openstack.secretName }}
                  key: OS_USER_DOMAIN_NAME
                {{- else }}
                value: "{{ .Values.openstack.OS_USER_DOMAIN_NAME }}"
                {{- end }}
              - name: OS_PROJECT_NAME
                {{- if .Values.openstack.enabled }}
                secretRef:
                  name: {{ .Values.openstack.secretName }}
                  key: OS_PROJECT_NAME
                {{- else }}
                value: "{{ .Values.openstack.OS_PROJECT_NAME }}"
                {{- end }}
              - name: OS_PROJECT_DOMAIN_NAME
                {{- if .Values.openstack.enabled }}
                secretRef:
                  name: {{ .Values.openstack.secretName }}
                  key: OS_PROJECT_DOMAIN_NAME
                {{- else }}
                value: "{{ .Values.openstack.OS_PROJECT_DOMAIN_NAME }}"
                {{- end }}
              - name: OS_REGION_NAME
                {{- if .Values.openstack.enabled }}
                secretRef:
                  name: {{ .Values.openstack.secretName }}
                  key: OS_REGION_NAME
                {{- else }}
                value: "{{ .Values.openstack.OS_REGION_NAME }}"
                {{- end }}
          restartPolicy: OnFailure
{{- end }}
