{{- if .Values.openstack.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.openstack.secretName }}
  labels:
    {{- include "snapshot-cli.labels" . | nindent 4 }}
type: Opaque
stringData:
  OS_AUTH_URL: {{ .Values.openstack.OS_AUTH_URL | quote }}
  OS_USERNAME: {{ .Values.openstack.OS_USERNAME | quote }}
  OS_PASSWORD: {{ .Values.openstack.OS_PASSWORD | quote }}
  OS_USER_DOMAIN_NAME: {{ .Values.openstack.OS_USER_DOMAIN_NAME | quote }}
  OS_PROJECT_NAME: {{ .Values.openstack.OS_PROJECT_NAME | quote }}
  OS_PROJECT_DOMAIN_NAME: {{ .Values.openstack.OS_PROJECT_DOMAIN_NAME | quote }}
  OS_REGION_NAME: {{ .Values.openstack.OS_REGION_NAME | quote }}
{{- end }}
